apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluegreen-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/mrcsury/gitops-bluegreen-demo.git
    targetRevision: main
    path: .

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
